### ISSUE TITLE
Social Media link broken

### ISSUE THREAD

**Issue by jbwhit** [alexhwoods/alexhwoods.com#1]
Clicking your LinkedIn link in the Social Media box, goes to: 

https://www.linkedin.com/in/alex-woods/96//

which has an extra trailing slash. But even after fixing that, I see: 

<img width="822" alt="screenshot 2015-07-22 12 05 13" src="https://cloud.githubusercontent.com/assets/105829/8834603/fb47c33c-3069-11e5-9af3-01e8b982ff1b.png">

Nice blog by the way!

**Comment by alexhwoods** [comment]
Thanks, I'll be sure to fix it!

**Comment by Frankri** [comment]
Hi,
thx for this interesting ipython notebook.
But I got a Syntaxerror
` File "<ipython-input-25-7012f8dcad7d>", line 16
    print(word, end=' ')`

What is wrong?
