### ISSUE TITLE
SyntaxError ?

### ISSUE THREAD

**Issue by Frankri** [alexhwoods/alexhwoods.com#2]
Hi,

thx for this inspiring notebook.
Sadly I get a SyntaxError in the 2nd. box

`File "<ipython-input-50-7012f8dcad7d>", line 16
    print(word, end=' ')
                   ^
SyntaxError: invalid syntax`

![bildschirmfoto 2015-08-10 um 15 51 18](https://cloud.githubusercontent.com/assets/2300206/9173047/d4dc6384-3f77-11e5-9ee7-b7a5a48a6ff6.png)

Can you help pls?

**Comment by alexhwoods** [comment]
Hey Frank,

Are you using Python 2? Because that's what it looks like. If you're not,
just try replacing that line with print(word, ' ').

I'll look at it in more depth when I get to a computer. Thanks for reading
my blog!
- Alex

**Comment by alexhwoods** [comment]
Just ran the code myself in python 2, and I got the same error you did.
Here is how to make it python 2 compatible -
print word + ' '

**Comment by Frankri** [comment]
Hi,

thx for your quick answer. I use Python 2.7.something. I will try your hint tomorrow - I live in Berlin (Germany) and we have near 11 pm. Give you a response asap.

Thank you and have nice day Frank

Am 10.08.2015 um 21:02 schrieb Alex Woods notifications@github.com:

> Just ran the code myself in python 2, and I got the same error you did.
> Here is how to make it python 2 compatible -
> print word + ' '
> 
> On Mon, Aug 10, 2015 at 11:31 AM Alexander Woods alexhwoods@gmail.com
> wrote:
> 
> > Hey Frank,
> > 
> > Are you using Python 2? Because that's what it looks like. If you're not,
> > just try replacing that line with print(word, ' ').
> > 
> > I'll look at it in more depth when I get to a computer. Thanks for reading
> > my blog!
> > - Alex
> >

**Comment by Frankri** [comment]
Thx, no longer an error with `word+' '`
